import type { Politico } from "./types";

const HOY = "2026-05-24";

export const POLITICOS: Politico[] = [
  {
    slug: "jenniffer-gonzalez-colon",
    nombre: "Jenniffer González-Colón",
    partido: "PNP",
    cargo: "Gobernador(a)",
    cargo_detalle: "Gobernadora de Puerto Rico",
    inicio_termino: "2025-01-02",
    fin_termino: "2029-01-02",
    bio: "Abogada y política. Sirvió como Comisionada Residente en Washington (2017-2025) antes de ser electa Gobernadora en las elecciones generales de noviembre de 2024.",
    redes: { web: "https://fortaleza.pr.gov" },
    promesas: [
      {
        id: "jgc-energia-01",
        titulo: "Reformar el sistema energético y reducir apagones",
        descripcion:
          "Plataforma del PNP 2024 — compromisos de estabilizar el servicio eléctrico, evaluar contratos con LUMA y Genera PR, y acelerar generación renovable.",
        fecha_promesa: "2024-09-15",
        estado: "por_verificar",
        sector: "energia",
        fuentes: [
          {
            titulo: "Plataforma de gobierno PNP 2024",
            tipo: "oficial",
            fecha: "2024-09-15",
          },
        ],
        confianza: "no_verificado",
        notas: "Pendiente vincular acciones específicas a la promesa.",
      },
      {
        id: "jgc-economia-01",
        titulo: "Atraer inversión y reducir trabas burocráticas",
        descripcion:
          "Compromiso de plataforma con simplificación de permisos y estímulo a la pequeña y mediana empresa.",
        fecha_promesa: "2024-09-15",
        estado: "por_verificar",
        sector: "economia",
        fuentes: [
          { titulo: "Plataforma de gobierno PNP 2024", tipo: "oficial" },
        ],
        confianza: "no_verificado",
      },
      {
        id: "jgc-seguridad-01",
        titulo: "Fortalecer la seguridad pública",
        descripcion:
          "Compromisos con la Policía de PR, atención a violencia de género, y coordinación con agencias federales.",
        fecha_promesa: "2024-09-15",
        estado: "por_verificar",
        sector: "seguridad",
        fuentes: [
          { titulo: "Plataforma de gobierno PNP 2024", tipo: "oficial" },
        ],
        confianza: "no_verificado",
      },
    ],
    medidas: [],
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [
        { titulo: "OEG - registro público", tipo: "oficial" },
      ],
    },
    fiscal: {
      periodo: "FY 2025-2026",
      fuentes: [
        { titulo: "OGP - Presupuesto Recomendado", tipo: "oficial" },
      ],
    },
    servicio: {
      town_halls_ultimos_12m: 0,
      notas: "Datos por confirmar.",
      fuentes: [{ titulo: "Fortaleza - prensa", tipo: "prensa" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: [
      { eje: "promesas", valor: null, confianza: "no_verificado", n_evidencias: 3, ultima_actualizacion: HOY, nota: "Datos demo." },
      { eje: "productividad", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY },
      { eje: "asistencia", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY, nota: "No aplica al ejecutivo." },
      { eje: "transparencia", valor: null, confianza: "no_verificado", n_evidencias: 1, ultima_actualizacion: HOY },
      { eje: "fiscal", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY },
      { eje: "constituyente", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY },
      { eje: "impacto", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY },
      { eje: "coherencia", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY },
      { eje: "sentimiento", valor: null, confianza: "no_verificado", n_evidencias: 0, ultima_actualizacion: HOY },
    ],
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "pablo-jose-hernandez-rivera",
    nombre: "Pablo José Hernández Rivera",
    partido: "PPD",
    cargo: "Comisionado(a) Residente",
    cargo_detalle: "Comisionado Residente en Washington",
    inicio_termino: "2025-01-03",
    fin_termino: "2029-01-03",
    bio: "Abogado. Electo Comisionado Residente en noviembre de 2024 representando al Partido Popular Democrático.",
    promesas: [
      {
        id: "pjh-relaciones-01",
        titulo: "Defender los fondos federales para Puerto Rico",
        descripcion:
          "Compromiso de campaña con la protección y expansión de fondos federales (Medicaid, Programas Nutricionales, fondos de recuperación).",
        fecha_promesa: "2024-10-01",
        estado: "por_verificar",
        sector: "economia",
        fuentes: [{ titulo: "Plataforma PPD 2024", tipo: "oficial" }],
        confianza: "no_verificado",
      },
    ],
    medidas: [],
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "House Ethics Committee", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "thomas-rivera-schatz",
    nombre: "Thomas Rivera Schatz",
    partido: "PNP",
    cargo: "Senador(a)",
    cargo_detalle: "Presidente del Senado",
    inicio_termino: "2025-01-02",
    bio: "Abogado. Presidente del Senado de Puerto Rico, cargo que ya había ocupado en cuatrienios anteriores.",
    promesas: [],
    medidas: [],
    asistencia: {
      periodo: "Sesión 2025",
      votos_totales: 0,
      votos_presentes: 0,
      comisiones_totales: 0,
      comisiones_presentes: 0,
      fuentes: [{ titulo: "Diario de Sesiones - Senado PR", tipo: "oficial" }],
    },
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "carlos-johnny-mendez-nunez",
    nombre: 'Carlos "Johnny" Méndez Núñez',
    partido: "PNP",
    cargo: "Representante",
    cargo_detalle: "Presidente de la Cámara de Representantes",
    inicio_termino: "2025-01-02",
    bio: "Abogado. Presidente de la Cámara de Representantes de Puerto Rico, cargo que también ocupó en el cuatrienio 2017-2021.",
    promesas: [],
    medidas: [],
    asistencia: {
      periodo: "Sesión 2025",
      votos_totales: 0,
      votos_presentes: 0,
      comisiones_totales: 0,
      comisiones_presentes: 0,
      fuentes: [
        { titulo: "Diario de Sesiones - Cámara PR", tipo: "oficial" },
      ],
    },
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "juan-dalmau-ramirez",
    nombre: "Juan Dalmau Ramírez",
    partido: "PIP",
    cargo: "Senador(a)",
    cargo_detalle: "Senador por Acumulación",
    inicio_termino: "2025-01-02",
    bio: "Abogado. Candidato a Gobernador por la Alianza de País (PIP-MVC) en 2024. Electo Senador por Acumulación.",
    promesas: [
      {
        id: "jdr-energia-01",
        titulo: "Cancelación del contrato con LUMA Energy",
        descripcion:
          "Compromiso reiterado en plataforma y campaña con la cancelación del contrato actual de operación del sistema de transmisión y distribución.",
        fecha_promesa: "2024-09-01",
        estado: "por_verificar",
        sector: "energia",
        fuentes: [{ titulo: "Plataforma Alianza de País 2024", tipo: "oficial" }],
        confianza: "no_verificado",
      },
    ],
    medidas: [],
    asistencia: {
      periodo: "Sesión 2025",
      votos_totales: 0,
      votos_presentes: 0,
      comisiones_totales: 0,
      comisiones_presentes: 0,
      fuentes: [{ titulo: "Diario de Sesiones - Senado PR", tipo: "oficial" }],
    },
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "manuel-natal-albelo",
    nombre: "Manuel Natal Albelo",
    partido: "MVC",
    cargo: "Senador(a)",
    cargo_detalle: "Senador por Acumulación",
    inicio_termino: "2025-01-02",
    bio: "Abogado. Líder del Movimiento Victoria Ciudadana. Excandidato a Alcalde de San Juan.",
    promesas: [],
    medidas: [],
    asistencia: {
      periodo: "Sesión 2025",
      votos_totales: 0,
      votos_presentes: 0,
      comisiones_totales: 0,
      comisiones_presentes: 0,
      fuentes: [{ titulo: "Diario de Sesiones - Senado PR", tipo: "oficial" }],
    },
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "jesus-manuel-ortiz-gonzalez",
    nombre: "Jesús Manuel Ortiz González",
    partido: "PPD",
    cargo: "Representante",
    cargo_detalle: "Portavoz de la Minoría — Cámara",
    inicio_termino: "2025-01-02",
    bio: "Representante por el Partido Popular Democrático. Presidente de la colectividad popular.",
    promesas: [],
    medidas: [],
    asistencia: {
      periodo: "Sesión 2025",
      votos_totales: 0,
      votos_presentes: 0,
      comisiones_totales: 0,
      comisiones_presentes: 0,
      fuentes: [{ titulo: "Diario de Sesiones - Cámara PR", tipo: "oficial" }],
    },
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "miguel-romero-lugo",
    nombre: "Miguel Romero Lugo",
    partido: "PNP",
    cargo: "Alcalde(sa)",
    cargo_detalle: "Alcalde de San Juan",
    region: "Región Capital",
    inicio_termino: "2025-01-13",
    bio: "Abogado. Alcalde de San Juan, capital de Puerto Rico.",
    promesas: [],
    medidas: [],
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    fiscal: {
      periodo: "FY 2025-2026",
      fuentes: [{ titulo: "OCAM", tipo: "oficial" }],
    },
    servicio: {
      town_halls_ultimos_12m: 0,
      notas: "Por verificar con la Oficina del Alcalde.",
      fuentes: [{ titulo: "Municipio de San Juan", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
  {
    slug: "luis-javier-hernandez-ortiz",
    nombre: "Luis Javier Hernández Ortiz",
    partido: "PPD",
    cargo: "Alcalde(sa)",
    cargo_detalle: "Alcalde de Villalba",
    region: "Región Sur Central",
    bio: "Alcalde del municipio de Villalba. Figura destacada del PPD a nivel municipal.",
    promesas: [],
    medidas: [],
    transparencia: {
      disclosures_a_tiempo: true,
      participa_datos_abiertos: false,
      casos: [],
      fuentes: [{ titulo: "OEG", tipo: "oficial" }],
    },
    servicio: {
      town_halls_ultimos_12m: 0,
      fuentes: [{ titulo: "Municipio de Villalba", tipo: "oficial" }],
    },
    impactos: [],
    coherencia: [],
    puntajes: defaultPuntajes(HOY),
    ultima_actualizacion: HOY,
    estado_dataset: "demo",
  },
];

function defaultPuntajes(fecha: string): Politico["puntajes"] {
  return (
    [
      "promesas",
      "productividad",
      "asistencia",
      "transparencia",
      "fiscal",
      "constituyente",
      "impacto",
      "coherencia",
      "sentimiento",
    ] as const
  ).map((eje) => ({
    eje,
    valor: null,
    confianza: "no_verificado" as const,
    n_evidencias: 0,
    ultima_actualizacion: fecha,
  }));
}

export function getPolitico(slug: string): Politico | undefined {
  return POLITICOS.find((p) => p.slug === slug);
}

export function getPoliticosPorPartido(partido: string): Politico[] {
  return POLITICOS.filter((p) => p.partido === partido);
}

export function getPoliticosPorCargo(cargo: string): Politico[] {
  return POLITICOS.filter((p) => p.cargo === cargo);
}
